### ISSUE TITLE
Crossterm conversion using incorrect colors

### ISSUE THREAD

**Issue by meain** [sharkdp/lscolors#40]
I am still not 100% certain on this and so I thought I would start a discussion around this. I believe we incorrectly converting to the bright variants in `crossterm` instead of the dark ones. For example `34` should be matched to `4` in `crossterm` which would be [`DarkBlue`](https://github.com/crossterm-rs/crossterm/blob/9a50fd2ce2701bb15f58722495024937143ad34d/src/style/types/color.rs#L130) and not [`Blue`](https://github.com/crossterm-rs/crossterm/blob/9a50fd2ce2701bb15f58722495024937143ad34d/src/style/types/color.rs#L138).

https://github.com/sharkdp/lscolors/blob/c6e191b91f637058ba932a4f7b065f2e19d8a1ba/src/style.rs#L58-L63

**Comment by sharkdp** [comment]
Thank you very much. This should be fixed. Ideally, we should have tests for both terminal library backends (that would assert that the output actually matches the correct escape sequene). I don't use the crossterm backend myself, so I hadn't noticed this.

**Comment by meain** [comment]
As of now `crossterm` does not seem to support 8/16 color terminals. The minimum you need is 256 colors(related [issue](https://github.com/crossterm-rs/crossterm/issues/495)). So, even if we are to change it to the dark varients(which we should still do), we will still get different output as `ansi-term` by default assumes 8 colors. For example, `LS_COLORS` value of `34` would become `1;34` in `ansi-term` and `38;5;4` in `crossterm`. The biggest difference that I have run into with this automatic conversion is that most terminals don't respect "use bright colors for bold text" if we are using 256 color pallete.
